import type {
  Amenity,
  Host,
  Location,
  Property,
  PropertyAmenity,
  PropertyImage,
  PropertyType,
  WishlistState,
} from "./model";

export const locations: Location[] = [
  {
    id: "loc_bali_canggu",
    city: "Canggu",
    province: "Bali",
    country: "Indonesia",
    displayName: "Canggu, Bali",
  },
  {
    id: "loc_bandung_lembang",
    city: "Lembang",
    province: "Jawa Barat",
    country: "Indonesia",
    displayName: "Lembang, Jawa Barat",
  },
  {
    id: "loc_yogyakarta_kaliurang",
    city: "Kaliurang",
    province: "DI Yogyakarta",
    country: "Indonesia",
    displayName: "Kaliurang, Yogyakarta",
  },
  {
    id: "loc_lombok_senggigi",
    city: "Senggigi",
    province: "Nusa Tenggara Barat",
    country: "Indonesia",
    displayName: "Senggigi, Lombok",
  },
];

export const propertyTypes: PropertyType[] = [
  { id: "type_villa", name: "Villa", slug: "villa" },
  { id: "type_apartment", name: "Apartment", slug: "apartment" },
  { id: "type_house", name: "House", slug: "house" },
  { id: "type_cabin", name: "Cabin", slug: "cabin" },
  { id: "type_guesthouse", name: "Guesthouse", slug: "guesthouse" },
];

export const hosts: Host[] = [
  {
    id: "host_001",
    name: "Made Pratama",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    joinedYear: 2019,
    isSuperhost: true,
  },
  {
    id: "host_002",
    name: "Ayu Lestari",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    joinedYear: 2020,
    isSuperhost: true,
  },
  {
    id: "host_003",
    name: "Raka Wibowo",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
    joinedYear: 2021,
    isSuperhost: false,
  },
];

export const amenities: Amenity[] = [
  { id: "amenity_pool", name: "Private Pool", iconName: "waves" },
  { id: "amenity_wifi", name: "Wi-Fi", iconName: "wifi" },
  { id: "amenity_kitchen", name: "Kitchen", iconName: "utensils" },
  { id: "amenity_parking", name: "Free Parking", iconName: "car" },
  { id: "amenity_ac", name: "Air Conditioning", iconName: "snowflake" },
  { id: "amenity_workspace", name: "Dedicated Workspace", iconName: "laptop" },
];

export const properties: Property[] = [
  {
    id: "prop_001",
    title: "Villa Tropis dengan Kolam Renang",
    slug: "villa-tropis-kolam-renang",
    description:
      "Villa tropis untuk keluarga dengan area terbuka, kolam renang pribadi, dan akses mudah ke pusat Canggu.",
    locationId: "loc_bali_canggu",
    propertyTypeId: "type_villa",
    hostId: "host_001",
    pricePerNight: 1_250_000,
    rating: 4.87,
    reviewCount: 128,
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    isGuestFavorite: true,
    createdAt: "2025-01-12T08:00:00.000Z",
    updatedAt: "2025-04-18T08:00:00.000Z",
  },
  {
    id: "prop_002",
    title: "Apartemen Modern Dekat Pantai",
    slug: "apartemen-modern-dekat-pantai",
    description:
      "Apartemen ringkas dengan balkon, dapur lengkap, dan akses cepat ke area pantai serta kafe populer.",
    locationId: "loc_bali_canggu",
    propertyTypeId: "type_apartment",
    hostId: "host_002",
    pricePerNight: 720_000,
    rating: 4.72,
    reviewCount: 86,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    isGuestFavorite: false,
    createdAt: "2025-02-04T08:00:00.000Z",
    updatedAt: "2025-04-10T08:00:00.000Z",
  },
  {
    id: "prop_003",
    title: "Rumah Keluarga di Udara Sejuk Lembang",
    slug: "rumah-keluarga-udara-sejuk-lembang",
    description:
      "Rumah luas dengan halaman, dapur keluarga, dan pemandangan perbukitan untuk liburan kelompok.",
    locationId: "loc_bandung_lembang",
    propertyTypeId: "type_house",
    hostId: "host_003",
    pricePerNight: 950_000,
    rating: 4.64,
    reviewCount: 64,
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    isGuestFavorite: true,
    createdAt: "2025-01-28T08:00:00.000Z",
    updatedAt: "2025-03-22T08:00:00.000Z",
  },
  {
    id: "prop_004",
    title: "Kabin Kayu Tenang di Kaliurang",
    slug: "kabin-kayu-tenang-kaliurang",
    description:
      "Kabin kayu hangat untuk pasangan atau keluarga kecil, dekat jalur alam dan area wisata Kaliurang.",
    locationId: "loc_yogyakarta_kaliurang",
    propertyTypeId: "type_cabin",
    hostId: "host_002",
    pricePerNight: 580_000,
    rating: 4.91,
    reviewCount: 42,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    isGuestFavorite: true,
    createdAt: "2025-03-03T08:00:00.000Z",
    updatedAt: "2025-05-01T08:00:00.000Z",
  },
  {
    id: "prop_005",
    title: "Guesthouse Nyaman untuk Remote Work",
    slug: "guesthouse-nyaman-remote-work",
    description:
      "Guesthouse tenang dengan Wi-Fi cepat, ruang kerja khusus, dan akses mudah ke pusat Lembang.",
    locationId: "loc_bandung_lembang",
    propertyTypeId: "type_guesthouse",
    hostId: "host_001",
    pricePerNight: 430_000,
    rating: 4.55,
    reviewCount: 39,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    isGuestFavorite: false,
    createdAt: "2025-02-17T08:00:00.000Z",
    updatedAt: "2025-04-09T08:00:00.000Z",
  },
  {
    id: "prop_006",
    title: "Villa Pantai Senggigi untuk Grup",
    slug: "villa-pantai-senggigi-grup",
    description:
      "Villa tepi pantai dengan empat kamar, kolam pribadi, dan area makan luar ruang untuk grup besar.",
    locationId: "loc_lombok_senggigi",
    propertyTypeId: "type_villa",
    hostId: "host_003",
    pricePerNight: 1_680_000,
    rating: 4.83,
    reviewCount: 111,
    maxGuests: 10,
    bedrooms: 4,
    beds: 6,
    bathrooms: 4,
    isGuestFavorite: true,
    createdAt: "2025-01-06T08:00:00.000Z",
    updatedAt: "2025-05-11T08:00:00.000Z",
  },
];

export const propertyImages: PropertyImage[] = [
  {
    id: "img_001_cover",
    propertyId: "prop_001",
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    altText: "Tampilan depan villa tropis dengan kolam renang",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_001_living",
    propertyId: "prop_001",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    altText: "Ruang keluarga villa tropis",
    sortOrder: 2,
    isCover: false,
  },
  {
    id: "img_002_cover",
    propertyId: "prop_002",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    altText: "Apartemen modern dengan balkon",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_003_cover",
    propertyId: "prop_003",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    altText: "Rumah keluarga dengan halaman hijau",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_004_cover",
    propertyId: "prop_004",
    imageUrl: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59",
    altText: "Kabin kayu di area pegunungan",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_005_cover",
    propertyId: "prop_005",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    altText: "Kamar guesthouse dengan meja kerja",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_006_cover",
    propertyId: "prop_006",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    altText: "Villa pantai dengan kolam renang",
    sortOrder: 1,
    isCover: true,
  },
  {
    id: "img_006_dining",
    propertyId: "prop_006",
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3",
    altText: "Area makan luar ruang villa pantai",
    sortOrder: 2,
    isCover: false,
  },
];

export const propertyAmenities: PropertyAmenity[] = [
  { propertyId: "prop_001", amenityId: "amenity_pool" },
  { propertyId: "prop_001", amenityId: "amenity_wifi" },
  { propertyId: "prop_001", amenityId: "amenity_kitchen" },
  { propertyId: "prop_001", amenityId: "amenity_ac" },
  { propertyId: "prop_002", amenityId: "amenity_wifi" },
  { propertyId: "prop_002", amenityId: "amenity_kitchen" },
  { propertyId: "prop_002", amenityId: "amenity_ac" },
  { propertyId: "prop_003", amenityId: "amenity_wifi" },
  { propertyId: "prop_003", amenityId: "amenity_kitchen" },
  { propertyId: "prop_003", amenityId: "amenity_parking" },
  { propertyId: "prop_004", amenityId: "amenity_wifi" },
  { propertyId: "prop_004", amenityId: "amenity_parking" },
  { propertyId: "prop_005", amenityId: "amenity_wifi" },
  { propertyId: "prop_005", amenityId: "amenity_workspace" },
  { propertyId: "prop_006", amenityId: "amenity_pool" },
  { propertyId: "prop_006", amenityId: "amenity_wifi" },
  { propertyId: "prop_006", amenityId: "amenity_kitchen" },
  { propertyId: "prop_006", amenityId: "amenity_parking" },
  { propertyId: "prop_006", amenityId: "amenity_ac" },
];

export const wishlistStates: WishlistState[] = [
  { propertyId: "prop_001", isWishlisted: false },
  { propertyId: "prop_002", isWishlisted: true },
  { propertyId: "prop_003", isWishlisted: false },
  { propertyId: "prop_004", isWishlisted: false },
  { propertyId: "prop_005", isWishlisted: true },
  { propertyId: "prop_006", isWishlisted: false },
];
